pipeline {
   agent any

   stages {
       stage('Checkout') {
           steps {
               git 'https://github.com/gauravkumar1207/JobPortal_Project'
           }
       }

       stage('Build') {
           steps {
               sh 'mvn clean install'
           }
       }

       stage('Test') {
           steps {
               sh 'mvn test'
           }
       }

       stage('Package') {
           steps {
               sh 'mvn package'
           }
       }
   }
}
